### ISSUE TITLE
Fullscreeni nupud ja mouse hover tekstid tõlkida

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#26]
![Screenshot 2019-09-24 at 12 48 20](https://user-images.githubusercontent.com/380007/65501536-d2ec3900-dec9-11e9-9c47-18d92c2b6cdf.png)
![Screenshot 2019-09-24 at 12 48 34](https://user-images.githubusercontent.com/380007/65501538-d2ec3900-dec9-11e9-91ed-00b7a1c2d8e1.png)

**Comment by pjotrsavitski** [comment]
Submitted a pull request. Translations should be updated with a next library release.
