### ISSUE TITLE
Teadmistekontrolli e-kiri vigane

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#29]
Materjal: https://sisuloome.e-koolikott.ee/node/253

- Kirjas vale pealkiri
- Sümbolid rea lõppudes

Saadetud kiri õpetajale:

Oled loonud uue Teadmistekontrolli pealkirjaga test.&#13;
Kasutusel olev õppematerjal: Loodusõpetus: maailmaruum.&#13;
&#13;
Teadmistekontroll on aktiivne alates Neljapäev, oktoober 17, 2019 - 10:05 kuni Neljapäev, oktoober 17, 2019 - 11:05 (kestus 1 tundi).&#13;
&#13;
Osalemisks vajalik kood on: 864031&#13;
&#13;
Tulemused on leitavad siit: https://sisuloome.e-koolikott.ee/h5p_challenge/509c1546-d584-4406-9a97-…;
Peale teadmistekontrolli lõppu saadetakse Teile e-kiri tulemustega. Tulemuste link on aktiivne kuni 36 tundi peale teadmistekontrolli lõppu.&#13;
&#13;
&#13;
Parimate soovidega,&#13;
Teadmistekontrolli meeskond.

![Screenshot 2019-10-17 at 11 18 23](https://user-images.githubusercontent.com/380007/66990973-dab98a80-f0cf-11e9-8e9a-b9a9d9a6a042.png)

**Comment by pjotrsavitski** [comment]
Fixed, see relese notes for more details: https://www.drupal.org/project/h5p_challenge/releases/8.x-1.0-rc2

Would still require service to be updated.

**Comment by pjotrsavitski** [comment]
Uuendatud.
