### ISSUE TITLE
Teadmistekontroll 2.0

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#32]
![Screenshot 2020-02-17 at 10 38 37](https://user-images.githubusercontent.com/380007/74636935-ae8f4280-5171-11ea-8641-20906be11c0d.png)

Teadmistekontrolli on võimalik luua ja läbida endiselt E-Koolikotti sisselogimata, kuid sisseloginud kasutaja puhul:
- ~Täidetakse automaatselt ära õpetaja e-posti aadress~
- ~Täidetakse automaatselt ära õpilase ees- ja perenimi~
- ~Salvestatakse tulemusi ilma kehtivuse piiranguta~
- ~Saab kasutaja sirvida kõiki alustatud Teadmistekontrolle~
- ~Ei saa kasutaja muuta e-posti aadressi või õpilase puhul ees- ja perenime~

Tulemuste lehel kuvatakse teadmistekontrolli koostajale (õpetaja) tabelit järgmise infoga:
**1. ~Järjekorra number~**
**2. ~Nimi~**
**3. ~Mastery level~**

- Kui total score = max score ja korduste arv = 1, on mastery level roheline
- Kui total score = 51% või kõrgem ja korduste arv on 2 või väiksem, on mastery level kollane
- Kui total score = vähem kui 50% või korduste arv on suurem kui 2, on mastery level punane

**4. ~Total score~**

- Total score = kõikide materjali sees olevate ülesannete punktisumma / maksimaalne punktisumma

**5. ~Üksiku küsimuse punktisumma kujul mitu mitmest~**

- Küsimuse pealkiri = Object definition description

**6. ~Kulunud aeg~**

- Teadmistekontrolli algusaeg (õpilane alustab teadmistekontrolli) kuni kas manuaalse lõpetamiseni või viimase ülesande vastamise aeg

**7. ~Katsete arv~**

![Screenshot 2020-02-26 at 14 04 56](https://user-images.githubusercontent.com/380007/75343382-08de8080-58a1-11ea-9367-8109aa3484ce.png)

**Comment by pjotrsavitski** [comment]
Pildil olev ajavahemiku tekst on vale. Kestvus mõjutab tulemuste nähtavuse aega, kuid hetkel on ta kuni 36 tundi peale kontrolli lõppu.
