### ISSUE TITLE
Teadmistekontroll kuvab õpilase alustamise ja lõpetamise aega

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#35]
Tulemuste tabelis kuvatakse iga õpilase kohta tema viimase katse alustamise ja lõpetamise aeg. Samuti salvestatakse ajad CSV-faili.

![Screenshot 2020-03-31 at 09 35 02](https://user-images.githubusercontent.com/380007/77994613-00131b80-7333-11ea-814c-48ec22847a76.png)

**Comment by pjotrsavitski** [comment]
Sai tehtud.
