### ISSUE TITLE
Kasutaja ei saa muuta oma profiilis e-posti aadressi

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#39]
E-posti välja muutes ja salvestades kuvatakse järgnev teade:

<img width="868" alt="Screenshot 2020-04-15 at 21 49 33" src="https://user-images.githubusercontent.com/380007/79376590-1344fe80-7f63-11ea-8282-098fabc02cc0.png">

HARID-iga sisse logides kontol lokaalset parooli ei ole.

**Comment by pjotrsavitski** [comment]
Kasutaja nime või e-posti aadressi muutmiseks on vaja praeguse salasõna välja täita (Praegune parool). Ilma selleta ei lubata neid välju muuta. HarID kasutajatel ei pruugi olla luba kohaliku salasõna sättimiseks (vaikimisi seda polegi). Antud pilt on pigem administraatori oma, seega sellele kontole piirangud ei kehti.

Seda võib lahendada kas [No Current Password](https://www.drupal.org/project/nocurrent_pass) mooduli abil või peaks oma enda koodiga midagi taolist lisama. Vastav muudatus mõjuks ainult HarID abil loodud kasutajakontodele.
