### ISSUE TITLE
Litsentsid ja litsentsiinfo

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#40]
- Metaandmete all on valikus vaid üks litsents, Attribution (CC BY)

![Screenshot 2020-04-23 at 12 29 50](https://user-images.githubusercontent.com/380007/80083938-dbd7e280-855e-11ea-917c-98522094fc0d.png)

- Muutmise/lisamise vaates kuvatakse autorile lehel teksti: "Materjalide avalikuks tegemisega nõustub kasutaja, et materjalile või kogumikule kohaldub Creative Commons’i litsents „Autorile viitamine + Jagamine samadel tingimustel 3.0 Eesti (CC BY-SA 3.0). See litsents kohaldub kõigile Sisuloomesse lisatavatele ja e-Koolikotis avalikus tehtavatele materjalidele. Juhul, kui kasutaja ei ole selle litsentsi kohaldamisega nõus, ei saa ta materjale avalikuks teha."

**Comment by tammets** [comment]
By publishing materials, author agrees on Creative Commons licence CC BY-SA 3.0. This licence applies to all published learning resources in Sisuloome and e-Koolikott. In case user is not going to agree on those terms, publishing materials is prohibited.

**Comment by pjotrsavitski** [comment]
Litsentsiks hakkab olema ikka CC BY-SA 3.0

**Comment by pjotrsavitski** [comment]
https://github.com/sisuloome/drupal/commit/429a2357baa0766cd02f411e3a38eaae4656a47f
