### ISSUE TITLE
Kasutajatel ei ole võimalik üles laadida JPG laiendiga faile

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#41]
jpg lubatud, JPG mitte. "White list of accepted files." muudab salvestamisel JPG->jpg.

**Comment by pjotrsavitski** [comment]
Kas piirangut paneb ette UI liides (JS) või lubatakse nii kaua kuni salvestamiseks läheb?

**Comment by tammets** [comment]
![2020-09-14 14 09 52](https://user-images.githubusercontent.com/380007/93078974-0eac7f80-f694-11ea-86cb-9403a3d2f8fb.gif)
