### ISSUE TITLE
Kasutaja saab valida materjali staatuse - mustand / avaldatud

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#5]

**Comment by pjotrsavitski** [comment]
[Selle](https://www.drupal.org/project/override_node_options) mooduli abil peaks olema võimalik midagi taolist saavutada. See aga tähendaks, et iga kasutaja saab suvaliselt hetkel oma avaldatud sisu staatust muuta.

See võimalus ei pruugi hästi toimida mitme autori kontekstis mida kirjeldatakse piletis #24
