### ISSUE TITLE
Lisada Google Analytics tracking code

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#6]
Info meilis.

**Comment by pjotrsavitski** [comment]
Hetkel ei toimi GA H5P Embed vaate puhul. Selleks on vaja vastavat vaadet laiendada.

**Comment by pjotrsavitski** [comment]
https://github.com/sisuloome/drupal/commit/ebc5362aed85f1b5d0e321b930c9b80da2a81ec7
