### ISSUE TITLE
Kasutajatel on võimalik valitud sisutüüpide juures kasutada matemaatilisi valemeid

### ISSUE THREAD

**Issue by tammets** [sisuloome/Sisuloome#7]
Funktsionaalselt sarnaselt kasutusel oleva vara.e-koolikott.ee lahendusele.

**Comment by leoste** [comment]
valemeid saab kasutada järgmistes sisutüüpides:
Accordion
Agamotto
Column
Dialog Cards
Dictation
Documentation Tool
Drag and Drop
Drag the Words
Essay
Fill in the Blanks
Guess the Answer
Mark the Words
Multiple Choice
Quiz
Single Choice Set
Summary
Table
Text
Timeline
True/False Question
